var MENU_1 = [
	['Usuário', null, null,
		['Cadastrar', 'frmUsuario.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=usuario&campos=2,3'],
		['Nível de administração', null, null,
			 ['Cadastrar', 'frmNivel.php?acao=adicionar'],
			 ['Gerenciar', 'gerenciar.php?tabela=nivel&campos=1'],
		 ],
	],
	['Pessoa', null, null,
	 	['Pessoa física', null, null,
		 	['Cadastrar', 'frmPessoafisica.php?acao=adicionar'],
			['Gerenciar', 'gerenciarPessoa.php?tabela=pessoafisica&campos=3,1,2'],
		],
		['Pessoa jurídica', null, null,
		 	['Cadastrar', 'frmPessoajuridica.php?acao=adicionar'],
			['Gerenciar', 'gerenciarPessoa.php?tabela=pessoajuridica&campos=5,1,2'],
		],
		['Contato', null, null,
		 	['Cadastrar', 'frmContato.php?acao=adicionar'],
			['Gerenciar', 'gerenciar.php?tabela=contato&campos=2,3'],
		],
	],
	['Movimentação', null, null,
	 	['Contas a receber', null, null,
			['Cadastrar', 'frmConta.php?acao=adicionar'],
			['Gerenciar', 'gerenciar.php?tabela=conta&campos=7,8'],
		],
		['Tipo de documento', null, null,
			['Cadastrar', 'frmTipodocumento.php?acao=adicionar'],
			['Gerenciar', 'gerenciar.php?tabela=tipodocumento&campos=1'],
		],
		['Periodicidade', null, null,
			['Cadastrar', 'frmPeriodicidade.php?acao=adicionar'],
			['Gerenciar', 'gerenciar.php?tabela=periodicidade&campos=1'],
		],
		['Banco', null, null,
			['Cadastrar', 'frmBanco.php?acao=adicionar'],
			['Gerenciar', 'gerenciar.php?tabela=banco&campos=1'],
		],
	]
];

var MENU_2 = [
	['Pessoa', null, null,
	 	['Pessoa física', null, null,
		 	['Cadastrar', '#'],
			['Gerenciar', 'gerenciarPessoa.php?tabela=pessoafisica&campos=3,1,2'],
		],
		['Pessoa jurídica', null, null,
		 	['Cadastrar', '#'],
			['Gerenciar', 'gerenciarPessoa.php?tabela=pessoajuridica&campos=5,1,2'],
		],
		['Contato', null, null,
		 	['Cadastrar', '#'],
			['Gerenciar', 'gerenciar.php?tabela=contato&campos=2,3'],
		],
	],
	['Movimentação', null, null,
	 	['Contas a receber', '#'],
	]
];