var MENU_1 = [
	['Acervo', null, null,
		['Cadastrar', 'frmAcervo.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=acervo&campos=6,4'],
		['Tipo Acervo', null, null,
			 ['Cadastrar', 'frmTipoAcervo.php?acao=adicionar'],
			 ['Gerenciar', 'gerenciar.php?tabela=tipoacervo&campos=1'],
		 ],
		['Autor', null, null,
			 ['Cadastrar', 'frmAutor.php?acao=adicionar'],
			 ['Gerenciar', 'gerenciar.php?tabela=autor&campos=1'],
		],
		['Editora', null, null,
			 ['Cadastrar', 'frmEditora.php?acao=adicionar'],
			 ['Gerenciar', 'gerenciar.php?tabela=editora&campos=1'],
		],	
	],
	['Locação', null, null,
		['Cadastrar', 'frmLocacao.php?acao=adicionar'],
		['Pendentes', 'gerenciar.php?tabela=locacao&campos=3,4'],
		['Todas', 'gerenciar.php?tabela=locacao&todas=sim&campos=3,4'],
	],
	['Usuários', null, null,
		['Cadastrar', 'frmUsuario.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=usuario&campos=1,2'],
	],
	['Administradores', null, null,
		['Cadastrar', 'frmAdministrador.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=administrador&campos=1,2'],
	],
	['Ferramentas', null, null,
	 	['Replicar Volumes', '../base/replicaVolumes.php']
	]
];