var MENU_1 = [
	['Empresa', null, null,
		['Cadastrar', 'frmEmpresa.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=empresa&campos=1'],
	],
	['Notícias', null, null,
		['Cadastrar', 'frmNoticia.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=noticia&campos=1'],
	],
	['Eventos', null, null,
		['Cadastrar', 'frmEvento.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=evento&campos=1'],
	],
	['Links', null, null,
		['Cadastrar', 'frmLink.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=link&campos=1'],
	],
	['Downloads', null, null,
		['Cadastrar', 'frmDownload.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=download&campos=1'],
	],
	['Parceiros', null, null,
		['Cadastrar', 'frmParceiro.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=parceiro&campos=2'],
	],
];