var MENU_1 = [
	['Usuário', null, null,
		['Cadastrar', 'frmUsuario.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=usuario&campos=2,3'],
		['Nível de administração', null, null,
			 ['Cadastrar', 'frmNivel.php?acao=adicionar'],
			 ['Gerenciar', 'gerenciar.php?tabela=nivel&campos=1'],
		 ],
	],
	['Cliente', null, null,
		['Cadastrar', 'frmCliente.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=cliente&campos=3'],
		['Grupo', null, null,
			 ['Cadastrar', 'frmGrupo.php?acao=adicionar'],
			 ['Gerenciar', 'gerenciar.php?tabela=grupo&campos=1'],
		 ],
	],
	['Agenda', null, null,
		['Cadastrar', 'frmAgenda.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=agenda&campos=7'],
		['Tipo', null, null,
			 ['Cadastrar', 'frmTipo.php?acao=adicionar'],
			 ['Gerenciar', 'gerenciar.php?tabela=tipo&campos=1'],
		 ],
	],
];

var MENU_2 = [
	['Usuário', null, null,
		['Cadastrar', 'frmUsuario.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=usuario&campos=2,3'],
		['Nível de administração', null, null,
			 ['Cadastrar', 'frmNivel.php?acao=adicionar'],
			 ['Gerenciar', 'gerenciar.php?tabela=nivel&campos=1'],
		 ],
	],
	['Cliente', null, null,
		['Cadastrar', 'frmCliente.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=cliente&campos=3'],
		['Grupo', null, null,
			 ['Cadastrar', 'frmGrupo.php?acao=adicionar'],
			 ['Gerenciar', 'gerenciar.php?tabela=grupo&campos=1'],
		 ],
	],
	['Agenda', null, null,
		['Cadastrar', 'frmAgenda.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=agenda&campos=7'],
		['Tipo', null, null,
			 ['Cadastrar', 'frmTipo.php?acao=adicionar'],
			 ['Gerenciar', 'gerenciar.php?tabela=tipo&campos=1'],
		 ],
	],
];

var MENU_3 = [
	['Cliente', null, null,
		['Cadastrar', 'frmCliente.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=cliente&campos=3'],
		['Grupo', null, null,
			 ['Cadastrar', 'frmGrupo.php?acao=adicionar'],
			 ['Gerenciar', 'gerenciar.php?tabela=grupo&campos=1'],
		 ],
	],
	['Agenda', null, null,
		['Cadastrar', 'frmAgenda.php?acao=adicionar'],
		['Gerenciar', 'gerenciar.php?tabela=agenda&campos=7'],
		['Tipo', null, null,
			 ['Cadastrar', 'frmTipo.php?acao=adicionar'],
			 ['Gerenciar', 'gerenciar.php?tabela=tipo&campos=1'],
		 ],
	],
];